import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';

const tickets = [{ id: 'regular', name: 'Regular', price: 1500, description: 'Standard entry' }, { id: 'vip', name: 'VIP', price: 5000, description: 'Premium viewing and fast-lane entry' }, { id: 'vvip', name: 'VVIP', price: 10000, description: 'Backstage access and lounge' }];

export default function EventDetailsPage() {
  const { id } = useParams();
  const [selected, setSelected] = useState<string | null>(null);
  return <main className="min-h-screen bg-gray-50"><nav className="bg-white shadow-sm"><div className="mx-auto flex max-w-7xl justify-between p-4"><Link to="/" className="text-2xl font-extrabold text-purple-700">OTIKO</Link><Link to="/explore">Explore</Link></div></nav><header className="bg-gradient-to-r from-purple-700 to-blue-800 py-16 text-white"><div className="mx-auto max-w-7xl px-4"><span className="rounded-full bg-white/20 px-3 py-1 text-sm">Concerts</span><h1 className="mt-3 text-4xl font-extrabold">Kenya Music Festival 2026</h1><p className="mt-2 text-purple-100">15 Sep 2026 · Kasarani Stadium · Nairobi</p></div></header><div className="mx-auto grid max-w-7xl gap-8 px-4 py-8 lg:grid-cols-3"><article className="space-y-6 lg:col-span-2"><section className="rounded-2xl bg-white p-7 shadow"><h2 className="text-2xl font-bold">About this event</h2><p className="mt-3 text-gray-600">A celebration of Kenyan music, culture, food, and community with performances from top artists across multiple stages.</p></section><section className="rounded-2xl bg-white p-7 shadow"><h2 className="text-2xl font-bold">Event details</h2><dl className="mt-4 grid gap-3 text-gray-600 md:grid-cols-2"><div><dt className="font-semibold text-gray-900">Date</dt><dd>15 September 2026</dd></div><div><dt className="font-semibold text-gray-900">Venue</dt><dd>Kasarani Stadium, Nairobi</dd></div></dl></section></article><aside className="h-fit rounded-2xl bg-white p-6 shadow lg:sticky lg:top-20"><h2 className="text-xl font-bold">Select tickets</h2><div className="mt-4 space-y-3">{tickets.map((ticket) => <button key={ticket.id} onClick={() => setSelected(ticket.id)} className={`w-full rounded-xl border p-4 text-left ${selected === ticket.id ? 'border-purple-700 bg-purple-50' : 'border-gray-200'}`}><strong>{ticket.name}</strong><span className="float-right text-purple-700">KSh {ticket.price.toLocaleString()}</span><p className="mt-1 text-sm text-gray-500">{ticket.description}</p></button>)}</div><Link to={selected ? `/checkout/${id}/${selected}` : '#'} className={`mt-6 block rounded-xl py-3 text-center font-bold ${selected ? 'bg-amber-600 text-white' : 'pointer-events-none bg-gray-200 text-gray-500'}`}>{selected ? 'Get tickets' : 'Select a ticket'}</Link></aside></div></main>;
}
