import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Icon } from '../../components/Icon';
import { isValidEmail } from '../../utils/validation';

export default function CheckoutPage() {
  const { eventId, ticketId } = useParams(); const [complete, setComplete] = useState(false); const [form, setForm] = useState({ name: '', email: '', phone: '' }); const [error, setError] = useState('');
  const price = ticketId === 'vip' ? 5000 : ticketId === 'vvip' ? 10000 : 1500;
  function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (!isValidEmail(form.email)) { setError('Enter a valid email address so we can send your tickets.'); return; } setComplete(true); }
  if (complete) return <main className="grid min-h-screen place-items-center bg-[#faf9fc] p-4"><section className="max-w-md rounded-3xl bg-white p-10 text-center shadow-xl"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-green-100 text-green-700"><Icon name="ticket" className="h-8 w-8" /></span><h1 className="mt-6 text-3xl font-black text-purple-900">Booking confirmed</h1><p className="mt-3 text-gray-600">Your ticket confirmation has been sent to <strong>{form.email}</strong>.</p><Link to="/explore" className="mt-7 inline-block rounded-xl bg-purple-700 px-6 py-3 font-bold text-white">Browse more events</Link></section></main>;
  return <main className="min-h-screen bg-[#faf9fc]"><nav className="border-b border-purple-100 bg-white"><div className="mx-auto flex h-[72px] max-w-6xl items-center justify-between px-4"><Link to="/" className="text-3xl font-black tracking-[-.08em] text-purple-800">OTIKO<span className="text-amber-500">.</span></Link><Link to={`/events/${eventId}`} className="text-sm font-bold text-purple-700">Back to event</Link></div></nav><div className="mx-auto grid max-w-5xl gap-8 px-4 py-12 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-3xl bg-white p-7 shadow-[0_12px_35px_rgba(45,26,78,.1)] sm:p-9"><p className="text-sm font-bold uppercase tracking-[.15em] text-amber-600">Secure checkout</p><h1 className="mt-2 text-3xl font-black tracking-tight">Complete your booking</h1><p className="mt-2 text-sm text-gray-500">Your tickets will be delivered by email after confirmation.</p><form onSubmit={submit} className="mt-8 space-y-5"><Field label="Full name"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your full name" /></Field><Field label="Email address"><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></Field><Field label="M-Pesa phone number"><input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+254 700 000 000" /></Field>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}<button className="w-full rounded-xl bg-gradient-to-r from-purple-700 to-indigo-700 py-3.5 font-bold text-white shadow-lg transition hover:brightness-110">Confirm and pay KSh {price.toLocaleString()}</button></form></section><aside className="h-fit rounded-3xl bg-purple-900 p-7 text-white shadow-xl"><p className="text-sm font-bold uppercase tracking-[.15em] text-amber-300">Order summary</p><h2 className="mt-4 text-2xl font-black">Kenya Music Festival</h2><p className="mt-2 flex items-center gap-2 text-sm text-purple-200"><Icon name="ticket" className="h-4 w-4" />{ticketId?.toUpperCase() ?? 'STANDARD'} ticket</p><div className="my-6 border-t border-white/15" /><div className="flex justify-between text-sm text-purple-100"><span>Ticket price</span><span>KSh {price.toLocaleString()}</span></div><div className="mt-4 flex justify-between text-lg font-black"><span>Total</span><span className="text-amber-300">KSh {price.toLocaleString()}</span></div><div className="mt-7 flex items-center gap-3 rounded-2xl bg-white/10 p-4 text-sm text-purple-100"><Icon name="shield" className="h-6 w-6 shrink-0 text-amber-300" />Your payment and ticket details are protected.</div></aside></div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-gray-700">{label}<span className="mt-1.5 block [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-gray-200 [&_input]:bg-gray-50 [&_input]:px-4 [&_input]:py-3 [&_input]:text-sm [&_input]:font-normal [&_input]:outline-none [&_input:focus]:border-purple-500 [&_input:focus]:bg-white [&_input:focus]:ring-2 [&_input:focus]:ring-purple-500/20">{children}</span></label>; }
